apiVersion: v1
kind: Namespace
metadata:
  name: service-sys

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pod
  namespace: service-sys
spec:
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: service-api
        image: service-amd64:0.1
        imagePullPolicy: Never
